name: CI

on:

  push:
    branches: [ "main" ]
    
env:
  BUCKET: applims.net


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
    - name: Install Dependences
      run: yarn install
      
      #Rodar testes Unitarios
      
    - name: Build
      run: yarn run build
      
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: Upload Files to Bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"
      
    - name: Allow puplic access
      run: gsutil -m acl ch -R AllUsers:R gs://"$BUCKET"
    
    
