name: CI

on:

  push:
    branches: [ "main" ]
    
env:
  BUCKET: applims.net


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with: 
        node-version: 16.x
        
    - name: Install dependencies
      run: yarn install

    # - name: Run tests
    #   run: yarn test --watchAll false
    
    - name: Build
      run: npm run build
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: Upload filed to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"
    
    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"
    
    # Set cache meta for static files
    - name: Set Cache-Control
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}

    # Set cache meta for index.html
    - name: Set Cache-Control
      run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
    
